appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
shippable:
  projectId: 5c32ce7dd1578b0700305b06
  secure: {BINSTAR_TOKEN: bkTdATvev7sVFsP62xFV2ck215nXEtH7eWXdhzRRtbzeKquSkNhTGTCoa5FcLDvAVe36w+Sv59/3/oWNyMood8pIWjHLMC5CqqLdc4NRmyyaCKWys4CLhTTurIBPFSWUilxZW1KCKv/WHOe+zQDi2o9R9lf5/MizuwThHSQOIcqeTIn4wtPzbne5MeKSW+mRCsb+l4E/Q1oY2w/mTJ+izDWkxefstZ2t8RqOxH6H20wwNOOj/1WdeztdCOtCAl99r8Aj58odGyfUMAEyw89c5HglAEPurBQs21DZbHp10NmgSLyIbukplulRUm+cQ37loT/hFfTjPUCqLEC3lu6SPw==}
travis:
  secure: {BINSTAR_TOKEN: TwIWtONZ9Ncaacn7g5BudgDedZyPi5WEtq7adcfvVIImZbCzxIDMIL7ZBeAIkxGQJ5xBeZvlnRtrjcrY5Tcpp5vvemwmQXgcBMx7v/yI4T41Vym7woi3uYJg7+tSMEJEhvzNDQmfx2VrnahtCD3r76PTQvON5rPuAEQQL09nvW3x4c/9miimpP1iH32cjHDO/w1/RuOgqCB/D90KGz89kz1KCQNQfa6Zs7UniEjmZBIGPs6LRfQY2rm/OJuuMgjmAgN9ZVXCK9DY/Qvuu/z7Djq2+E+r8c5uAfjCOyGswMTu4tOYbU9P/oUNaaRkXQIUkqxqBOCutRjCzTHbtIG0YlG8qaWEixSK3WPQN8ke6pxs01oB6p54PvcLp1qeb63nTwyXJcGqYEDooj5gSDdgfwo/fF/FMKlA4iXJ/Ps8+1XAq8N6k/2Y/m37IeGHb22c+SmVaTUfVtw79Yl83Or9jCyq7/WdnRFKyVPpAJryYt1NSUTUr9ELh8uSY0sibxB/UwoP8ctY/OSpL8bcuz39mlEFkz1vlghyqQEiCHYCOg/mRj3aOXhi4TOrYdkl0JzTpy2td2NGUt4gcIDVzsog7z1I7tqe+OoCdoM9ulc5rrBRQn9GkPmjdCRu4AaNPidF61TSomOLM1Fim2F2fbOR85HeflbCj4Cg7/MQfBLO29I=}
